name: chatview_connect_example
description: "Flutter project integrating chatview with chatview_connect package."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  uuid: ^4.5.1
  intl:
  audio_waveforms: ^2.0.1
  chatview: ^3.0.0
  flutter_svg: ^2.1.0

  chatview_connect:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/vectors/
  uses-material-design: true
